DEFAULT_MODEL: str = "all-MiniLM-L6-v2"

DEFAULT_CHUNK_OVERLAP: int = 1
DEFAULT_SEMANTIC_CHUNK_SIZE: int = 4

DEFAULT_SEARCH_LIMIT: int = 5
DEFAULT_BM25_K1: float = 1.5
DEFAULT_BM25_B: float = 0.75

SCORE_PRECISION = 3
